name: ifes_solar
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^0.13.4
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  pdfx: ^2.6.0
  google_maps_flutter: ^2.6.1
  fl_chart: ^0.67.0
  intl: ^0.19.0
  internet_file: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon-2.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: NeoSansStd
      fonts:
        - asset: assets/fonts/NeoSansStd-Regular.otf
          weight: 400
        - asset: assets/fonts/NeoSansStd-Medium.otf
          weight: 500
        - asset: assets/fonts/NeoSansStd-Bold.otf
          weight: 700
